version: '3.1'

services:
  db:
    image: postgres:alpine3.19
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ecms_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: zxc